### ISSUE TITLE
problem with dependices

### ISSUE THREAD

**Issue by hdmotion** [boxingsquirrel/iDeviceActivator#1]
can not satisfy dependencies (libplist, libgtk) on Ubuntu 10.04 LTS - Lucid Lynx.

Can you tell your distro, version and repo sources?

**Comment by boxingsquirrel** [comment]
I use Debian, but the Ubuntu repos should have the stuff you need...should be libplist-dev and libgtk2.0-dev...

**Comment by hdmotion** [comment]
sudo apt-get install libplist-dev libgtk2.0-dev
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libplist-dev is already the newest version.
libgtk2.0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

---

eugene@eugene-desktop:~$ dpkg -i iDeviceActivator_0.1_i386.deb 
dpkg: requested operation requires superuser privilege
eugene@eugene-desktop:~$ sudo dpkg -i iDeviceActivator_0.1_i386.deb 
Selecting previously deselected package ideviceactivator.
(Reading database ... 161891 files and directories currently installed.)
Unpacking ideviceactivator (from iDeviceActivator_0.1_i386.deb) ...
dpkg: dependency problems prevent configuration of ideviceactivator:
 ideviceactivator depends on libplist; however:
  Package libplist is not installed.
 ideviceactivator depends on libgtk; however:
  Package libgtk is not installed.
dpkg: error processing ideviceactivator (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils ...
Processing triggers for python-gmenu ...
Rebuilding /usr/share/applications/desktop.ru_RU.utf8.cache...
Processing triggers for python-support ...
Errors were encountered while processing:
 ideviceactivator

**Comment by hdmotion** [comment]
make && sudo make install
tar -cvzf source.tar.gz data res src CREDITS README Makefile iDeviceActivator.desktop
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
src/
src/ideviceactivate.o
src/activate.c
src/gtk-activator.c
src/ui.glade
src/activate.o
src/activate.h
src/file.h
src/device.o
src/file.c
src/ui.o
src/cache.h
src/cache.o
src/cache.c
src/util.h
src/file.o
src/ui.h
src/device.c
src/util.o
src/idevice.h
src/device.h
src/ui.c
src/name_prompt.glade
src/util.c
src/ideviceactivate.c
src/gtk-activator.o
CREDITS
README
Makefile
iDeviceActivator.desktop
gcc -o iDeviceActivator src/gtk-activator.o src/device.o src/file.o src/ui.o src/activate.o src/ideviceactivate.o src/cache.o src/util.o -limobiledevice -lplist -lcurl `pkg-config --libs gtk+-2.0` -lzip
gtk-builder-convert src/ui.glade res/ui.xml
Wrote res/ui.xml
gtk-builder-convert src/name_prompt.glade res/name_prompt.xml
Wrote res/name_prompt.xml

Run 'make install' as root to install
tar -cvzf binary.tar.gz data res CREDITS README iDeviceActivator
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
CREDITS
README
iDeviceActivator
rm -rf dpkg/usr
mkdir dpkg/usr
mkdir: cannot create directory `dpkg/usr': No such file or directory
make: **\* [deb] Error 1

---

## mkdir dpkg

make && sudo make install
tar -cvzf source.tar.gz data res src CREDITS README Makefile iDeviceActivator.desktop
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
src/
src/ideviceactivate.o
src/activate.c
src/gtk-activator.c
src/ui.glade
src/activate.o
src/activate.h
src/file.h
src/device.o
src/file.c
src/ui.o
src/cache.h
src/cache.o
src/cache.c
src/util.h
src/file.o
src/ui.h
src/device.c
src/util.o
src/idevice.h
src/device.h
src/ui.c
src/name_prompt.glade
src/util.c
src/ideviceactivate.c
src/gtk-activator.o
CREDITS
README
Makefile
iDeviceActivator.desktop
gcc -o iDeviceActivator src/gtk-activator.o src/device.o src/file.o src/ui.o src/activate.o src/ideviceactivate.o src/cache.o src/util.o -limobiledevice -lplist -lcurl `pkg-config --libs gtk+-2.0` -lzip
gtk-builder-convert src/ui.glade res/ui.xml
Wrote res/ui.xml
gtk-builder-convert src/name_prompt.glade res/name_prompt.xml
Wrote res/name_prompt.xml

Run 'make install' as root to install
tar -cvzf binary.tar.gz data res CREDITS README iDeviceActivator
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
CREDITS
README
iDeviceActivator
rm -rf dpkg/usr
mkdir dpkg/usr
mkdir dpkg/usr/local
mkdir dpkg/usr/local/bin
mkdir dpkg/usr/local/share
mkdir dpkg/usr/local/share/iDeviceActivator
mkdir dpkg/usr/local/share/iDeviceActivator/res
mkdir dpkg/usr/local/share/iDeviceActivator/data
mkdir dpkg/usr/share
mkdir dpkg/usr/share/applications
cp iDeviceActivator dpkg/usr/local/bin
cp res/\* dpkg/usr/local/share/iDeviceActivator/
cp data/\* dpkg/usr/local/share/iDeviceActivator/
cp iDeviceActivator.desktop dpkg/usr/share/applications/iDeviceActivator.desktop
dpkg -b dpkg iDeviceActivator_0.1_i386.deb
dpkg-deb: failed to open package info file `dpkg/DEBIAN/control' for reading: No such file or directory

## make: **\* [deb] Error 2

cd dpkg
mkdir DEBIAN
cp ../../iDeviceActivator_Deb_Downloaded_And_Unpacked/control/\* DEBIAN/

## cd ..

iDeviceActivator$ make && sudo make install
tar -cvzf source.tar.gz data res src CREDITS README Makefile iDeviceActivator.desktop
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
src/
src/ideviceactivate.o
src/activate.c
src/gtk-activator.c
src/ui.glade
src/activate.o
src/activate.h
src/file.h
src/device.o
src/file.c
src/ui.o
src/cache.h
src/cache.o
src/cache.c
src/util.h
src/file.o
src/ui.h
src/device.c
src/util.o
src/idevice.h
src/device.h
src/ui.c
src/name_prompt.glade
src/util.c
src/ideviceactivate.c
src/gtk-activator.o
CREDITS
README
Makefile
iDeviceActivator.desktop
gcc -o iDeviceActivator src/gtk-activator.o src/device.o src/file.o src/ui.o src/activate.o src/ideviceactivate.o src/cache.o src/util.o -limobiledevice -lplist -lcurl `pkg-config --libs gtk+-2.0` -lzip
gtk-builder-convert src/ui.glade res/ui.xml
Wrote res/ui.xml
gtk-builder-convert src/name_prompt.glade res/name_prompt.xml
Wrote res/name_prompt.xml

Run 'make install' as root to install
tar -cvzf binary.tar.gz data res CREDITS README iDeviceActivator
data/
data/current.plist
data/img.plist
data/latest.plist
res/
res/ui.xml
res/iPhone.png
res/iPad.png
res/iPod.png
res/name_prompt.xml
CREDITS
README
iDeviceActivator
rm -rf dpkg/usr
mkdir dpkg/usr
mkdir dpkg/usr/local
mkdir dpkg/usr/local/bin
mkdir dpkg/usr/local/share
mkdir dpkg/usr/local/share/iDeviceActivator
mkdir dpkg/usr/local/share/iDeviceActivator/res
mkdir dpkg/usr/local/share/iDeviceActivator/data
mkdir dpkg/usr/share
mkdir dpkg/usr/share/applications
cp iDeviceActivator dpkg/usr/local/bin
cp res/\* dpkg/usr/local/share/iDeviceActivator/
cp data/\* dpkg/usr/local/share/iDeviceActivator/
cp iDeviceActivator.desktop dpkg/usr/share/applications/iDeviceActivator.desktop
dpkg -b dpkg iDeviceActivator_0.1_i386.deb
dpkg-deb: building package `ideviceactivator' in`iDeviceActivator_0.1_i386.deb'.
Installing 1 file to /usr/local/bin...
cp ./iDeviceActivator /usr/local/bin/iDeviceActivator
Installing 4 files to /usr/local/share/iDeviceActivator...
rm -rf /usr/local/share/iDeviceActivator
mkdir /usr/local/share/iDeviceActivator
mkdir /usr/local/share/iDeviceActivator/res /usr/local/share/iDeviceActivator/data
cp ./res/\* /usr/local/share/iDeviceActivator/res
cp ./data/\* /usr/local/share/iDeviceActivator/data
Adding iDeviceActivator to the menu...
cp iDeviceActivator.desktop /usr/share/applications/iDeviceActivator.desktop
Install complete
To remove run 'make uninstall' as root

**Comment by hdmotion** [comment]
---

## now app is ready, but

~$ iDeviceActivator
INFO: Retriving device list
INFO: Opening device
INFO: Started lockdownd
.
INFO: Read sucessfully from /usr/local/share/iDeviceActivator/data/img.plist
Creating activation request
Segmentation fault
eugene@eugene-desktop:~$
